      'stt1_my_vi_tnh_msi_pro_dp180_a': {
        name: 'Máy vi tính MSI PRO DP180 AI 8HG',
        model: '', brand: 'MSI', origin: '', warranty: '', unit: 'Cái', price: 0,
        specs: [
          { key: 'CPU', value: 'Intel® Core™ Ultra 5 225' },
          { key: 'RAM', value: '16GB DDR5' },
          { key: 'Ổ cứng', value: '512GB SSD' },
          { key: 'Cổng xuất hình', value: 'HDMI;' },
          { key: 'Thông số', value: 'Màn hình 23.8 inch' },
          { key: 'Hệ điều hành', value: 'Window 11 Pro 64 bit bản quyền vĩnh viễn' },
          { key: 'Thông số', value: 'Phần mềm Microsoft Office Home & Business 2024' },
          { key: 'Hình thức cấp phép', value: 'Key điện tử' },
          { key: 'Thời hạn bản quyền', value: 'Vĩnh viễn' },
          { key: 'Ngôn ngữ', value: 'Nhiều ngôn ngữ' },
          { key: 'Tương thích hệ điều hành', value: 'Windows, MacOS, Android IOS' },
          { key: 'Thông số', value: 'Phần mềm diệt virus bản quyền 03 năm' },
          { key: 'Thông số', value: 'Chuột bàn phím đi kèm' },
          { key: 'Kết nối không dây, Wifi, Bluetooth', value: 'không' },
          { key: 'Thông số', value: 'Bảo hành 12 tháng' }
        ]
      },
      'stt2_my_in_oki_b433dn': {
        name: 'Máy in OKI B433DN',
        model: '', brand: 'OKI', origin: '', warranty: '', unit: 'Cái', price: 0,
        specs: [
          { key: 'Tốc độ in A4/Letter', value: 'lên đến 40 trang/phút' },
          { key: 'Loại máy in', value: 'Đơn năng Laser' },
          { key: 'In đảo mặt', value: 'Có' },
          { key: 'Độ phân giải', value: '1200 x 1200 dpi' },
          { key: 'Kết nối', value: 'Ethernet: 1000BASE-T/100BASE-TX/10BASE-T,\nUSB 2.0 Thiết bị (Loại B), USB 2.0 Máy chủ, NFC8' },
          { key: 'Nguồn điện', value: '220-240 V AC 50/60Hz' },
          { key: 'Thông số', value: 'Bảo hành 12 tháng' }
        ]
      },
      'stt3_my_scan_ricoh_fi8170': {
        name: 'Máy scan RICOH Fi-8170',
        model: '', brand: 'Ricoh', origin: '', warranty: '', unit: 'Cái', price: 0,
        specs: [
          { key: 'Tốc độ quét ADF', value: '70 trang/phút, 140 hình/phút.' },
          { key: 'Độ phân giải máy quét', value: '600 x 600 dpi.' },
          { key: 'Kết nối', value: 'USB 3.2 Gen1x1 / USB 2.0 / USB 1.1\nLAN: 10BASE-T, 100BASE-TX, 1000BASE-T' },
          { key: 'Bộ nhớ', value: '512 MB' },
          { key: 'Tốc độ xử lý', value: 'GI Processor 666 Mhz' },
          { key: 'Chu kì quét (daily)', value: '10000 trang/ ngày' },
          { key: 'Định dạng file quét', value: 'Bitmap, TIFF, Multi-TIFF, JPEG, JPEG2000, Searchable PDF, PDF, PDF/A, PNG, RTF, Word, Excel, PowerPoint' },
          { key: 'Thông số', value: 'Bảo hành 12 tháng' }
        ]
      },
      'stt4_my_nh_ph_kin_canon_eos_r6': {
        name: 'Máy ảnh + phụ kiện Canon EOS R6 Mark II',
        model: '', brand: 'Canon', origin: '', warranty: '', unit: 'Cái', price: 0,
        specs: [
          { key: 'Thông số', value: 'Cảm biến Full-Frame 24,2MP' },
          { key: 'ISO', value: '100 đến 102.400' },
          { key: 'Thông số', value: 'Quay video 4K' },
          { key: 'Thông số', value: 'Quay khung dọc dễ dàng' },
          { key: 'Phụ kiện đi kèm', value: '' },
          { key: 'Ống kính đi kèm', value: 'RF 50mm' },
          { key: 'Thông số', value: 'Pin đi kèm' },
          { key: 'Thông số', value: 'Thẻ nhớ 64GB đi kèm' },
          { key: 'Thông số', value: 'Chân máy ảnh' },
          { key: 'Thông số', value: 'Đèn chụp' },
          { key: 'Thông số', value: 'Phông chụp' },
          { key: 'Thông số', value: 'Bảo hành 12 tháng' }
        ]
      },
      'stt5_thit_b_switch_layer_3_gra': {
        name: 'Thiết bị Switch layer 3 Granstream GWN7813',
        model: '', brand: 'Granstream', origin: '', warranty: '', unit: 'Cái', price: 0,
        specs: [
          { key: 'Thiết bị chính', value: '' },
          { key: 'Thông số', value: '24x10/100/1000BASE-T (RJ-45)' },
          { key: 'Thông số', value: '4x10GBASE-R (SFP+)/1000BASE-X (SFP)' },
          { key: 'Thông số', value: '1xConsole port RJ-45' },
          { key: 'Thiết bị đi kèm', value: '' },
          { key: 'Số kết nối', value: '4 sim + 1 Ethernet' },
          { key: 'Băng tần wifi', value: '2.4GHz, 5.8GHz' },
          { key: 'Wifi', value: '802.11b/g/n, tốc độ 300Mb/s' },
          { key: 'Phạm vi phát wifi', value: '30m' },
          { key: 'Pin tích hợp', value: '10.000 mA' },
          { key: 'Thời gian hoạt động', value: '5,5 giờ' },
          { key: 'Màn hình hiển thị các thông tin', value: 'Tình trạng pin; băng thông đường lên; băng thông đường xuống; tình trạng kết nối các sim; tình trạng mức sóng trên các sim' },
          { key: 'Hỗ trợ Ipv6', value: 'có' },
          { key: 'Thông số', value: 'Cho phép cấu hình riêng biệt từng sim, LAN, WAN, Wifi' },
          { key: 'Cho phép kiểm tra trạng thái trên từng sim bao gồm', value: 'Tình trạng hoạt động; tên nhà mạng; mức tín hiệu; băng thông sử dụng; IMEI; IMSI.' },
          { key: 'Số kết nối ăng ten', value: '6' },
          { key: 'Thiết kế', value: 'Tích hợp trong valy cứng' },
          { key: 'Cấp độ bảo vệ', value: 'IP67' },
          { key: 'Thông số', value: 'Bảo hành 12 tháng' }
        ]
      },
      'stt6_my_ch_liveu_lu2000': {
        name: 'Máy chủ  LiveU LU2000',
        model: '', brand: 'LiveU', origin: '', warranty: '', unit: 'Cái', price: 0,
        specs: [
          { key: 'CPU', value: 'Intel Xeon E-2124 tương đương hoặc cao hơn' },
          { key: 'Ram', value: '16 GB DDR 4' },
          { key: 'Ổ cứng', value: '1 TB HDD' },
          { key: 'VGA', value: 'N/A' },
          { key: 'Thông số', value: 'Chế độ xem dạng danh sách; chế độ xem dạng ô' },
          { key: 'Thông số', value: 'Lọc thiết bị phát hình theo tình trạng hoạt động (đang truyền, đang online, đang offline)' },
          { key: 'Thông số', value: 'Khả năng quản lý kênh truyền' },
          { key: 'Thông số', value: 'Xem danh sách kênh' },
          { key: 'Thông số', value: 'Thông tin kênh (tên, chế độ, cổng xuất hình, ép độ phân giải đầu ra, hạn chế băng thông)' },
          { key: 'Thông số', value: 'Bật tắt, chỉnh sửa lớp phủ đồ họa' },
          { key: 'Thông số', value: 'Hỗ trợ stream RTSP; MPEG-TS; SRT; RTMP' },
          { key: 'Hỗ trợ stream lên những nền tảng', value: 'Akamai; Facebook; Youtube; Twitch; Ustream; Wowza;...' },
          { key: 'Thông số', value: 'Cài đặt độ phân giải, bitrate cho stream' },
          { key: 'Thông số', value: 'Cho phép xem thông tin thiết bị phát hình' },
          { key: 'Thông số', value: 'Chế độ hoạt động' },
          { key: 'Thông số', value: 'Các tệp hiện có (trong bộ nhớ, thẻ SD, USB)' },
          { key: 'Thông số', value: 'Xem trước video đang truyền' },
          { key: 'Thông số', value: 'Kênh đang truyền về' },
          { key: 'Thông số', value: 'Tình trạng kết nối' },
          { key: 'Thông số', value: 'Tên; S/N; Phiên bản phần mềm;...' },
          { key: 'Thông số', value: 'Vị trí thiết bị trên bản đồ' },
          { key: 'Điều khiển thiết bị phát từ xa', value: '' },
          { key: 'Thông số', value: 'Điều khiển truyền/dừng truyền' },
          { key: 'Thông số', value: 'Lựa chọn kênh truyền' },
          { key: 'Thông số', value: 'Cấu hình độ trễ truyền' },
          { key: 'Thông số', value: 'Cấu hình chế độ hoạt động' },
          { key: 'Thông số', value: 'Kết nối/ngắt kết nối wifi, ethernet' },
          { key: 'Thông số', value: 'Kết nối/ngắt kết nối toàn bộ modem SIM hoặc từng modem SIM' },
          { key: 'Thông số', value: 'Khả năng quản lý danh sách tệp đã truyền về server' },
          { key: 'Thông số', value: 'Tìm kiếm tệp' },
          { key: 'Thông số', value: 'Xóa tệp' },
          { key: 'Thông số', value: 'Lọc các tệp theo thiết bị tải lên' },
          { key: 'Thông số', value: 'Xem siêu dữ liệu (meta data) của tệp' },
          { key: 'Thông số', value: 'Cài đặt mật khẩu' },
          { key: 'Thông số', value: 'Cài đặt thông báo khi' },
          { key: 'Thông số', value: 'Thiết bị online' },
          { key: 'Thông số', value: 'Bắt đầu truyền video' },
          { key: 'Thông số', value: 'Dừng truyền video' },
          { key: 'Thông số', value: 'Thiết bị offline do để quá lâu' },
          { key: 'Thông số', value: 'Thiết bị offline khi đang truyền video' },
          { key: 'Thông số', value: 'Đang truyền file' },
          { key: 'Thông số', value: 'Truyền file hoàn thành' },
          { key: 'Thông số', value: 'Có thiết bị mới được thêm vào' },
          { key: 'Module truyền dẫn tín hiệu', value: '' },
          { key: 'Độ phân giải video', value: '1080p50/60/25/30, 720p50/60' },
          { key: 'Giao diện video', value: 'HDMI và Ethernet RJ45 cho IP camera' },
          { key: 'VIDEO encoder', value: 'H.265/HEVC, H.264' },
          { key: 'AUDIO encoder', value: 'AAC-HE/LC, 2 kênh audio' },
          { key: 'Mang theo người', value: 'Túi đựng chuyên nghiệp, có đai thắt hoặc giá trên camera' },
          { key: 'Thông số', value: 'Cộng gộp băng thông đồng thời' },
          { key: 'Lên tới 6 đường', value: '2 x modem trong 4G, 2 x modem ngoài 4G, 01 WiFi và 01 Ethernet' },
          { key: 'Mã hóa', value: 'AES256' },
          { key: 'Nhiều đầu ra', value: 'Nhiều đầu ra A/V thông qua các luồng SDI và stream H.264 bao gồm kết nối CDN (phía máy chủ)' },
          { key: 'Nguồn cấp', value: 'Pin 3 giờ tích hợp trong, Bộ chuyển đổi nguồn DC12-19V; Pin ngoài' },
          { key: 'Điều khiển tại chỗ', value: 'Điều khiển bằng nút xoay và giám sát trên màn hình 2.2 inch' },
          { key: 'Điều khiển từ xa', value: 'Điều khiển từ xa từ điện thoại thông minh, máy tính xách tay, máy tính bảng thông qua trình duyệt web' },
          { key: 'Hiển thị thông tin', value: 'Xem trước video; tình trạng kết nối di động trên mỗi mạng bao gồm băng thông, độ trễ mạng, vv' },
          { key: 'Khả năng phục hồi và chất lượng', value: 'Chất lượng và khả năng phục hồi video hàng đầu nhờ các thuật toán như (ABR), tự động sửa lỗi (FEC) và các thuật toán phục hồi dữ liệu mật;' },
          { key: 'Giao diện', value: '2 x USB 2.0, micro USB, RJ-45 Ethernet, 3.5mm in/out audio jack, micro-SD card, khe cắm SIM' },
          { key: 'Giao diện không dây', value: 'WiFi 802.11 a,b,g,n,ac hỗ trợ ăng-ten MIMO, 4G / 5G' },
          { key: 'Kích thước', value: '112.5mm x 203mm x 54.5mm / 4.4” x 8” x 2.1” (W x H x D)' },
          { key: 'Trọng lượng', value: '955g (2.1lbs) với hai modem 3G/4G và pin bên trong' },
          { key: 'Chống rung sốc', value: 'MIL STD 810G method 514.6' },
          { key: 'Nhiệt độ hoạt động', value: '-5C đến +45C (23F đến 113F)' },
          { key: 'Thông số', value: 'Bảo hành 12 tháng' }
        ]
      },
      'stt7_cng_di_ng_wdbbgb0120hbkse': {
        name: 'Ổ cứng di động WDBBGB0120HBK-SESN',
        model: '', brand: 'WD', origin: '', warranty: '', unit: 'Cái', price: 0,
        specs: [
          { key: 'Kích thước', value: '3.5 inch' },
          { key: 'Giao tiếp', value: '1 cổng USB 3.0 tương thích USB 2.0' },
          { key: 'Tốc độ kết nối', value: '5Gb/s (max)' },
          { key: 'Dung lượng', value: '12 TB' },
          { key: 'Màu sắc', value: 'Vỏ nhựa màu đen' },
          { key: 'Kích thước vật lý', value: '170.6 × 49 × 139.3 mm; nặng: 0.97kg' },
          { key: 'Thông số', value: 'Đặt đứng nhỏ gọn trên bàn làm việc.' },
          { key: 'Nhiệt độ', value: '' },
          { key: 'Hoạt động', value: '5°C to 35°C;' },
          { key: 'Không hoạt động', value: '-20°C to 65°C' },
          { key: 'Tương thích', value: 'Windows/Mac; đã được định dạng sẵn exFAT. cho Windows (Không cần định dạng lại cho MAC OS X)' },
          { key: 'Thông số', value: 'Bảo hành 12 tháng' }
        ]
      },
      'stt8_mn_hnh_tivi_55_inch_sharp': {
        name: 'Màn hình Tivi 55 inch Sharp 4T-C55FM2X',
        model: '', brand: 'Sharp', origin: '', warranty: '', unit: 'Cái', price: 0,
        specs: [
          { key: 'Kích cỡ', value: '55 inch' },
          { key: 'Độ phân giải', value: '4K UHD (3840 x 2160).' },
          { key: 'Tấm nền', value: 'Full-Array LED backlighting' },
          { key: 'Độ sáng', value: '300 nits' },
          { key: 'Tần số quét', value: '60 Hz' },
          { key: 'Thông số', value: 'Bảo hành 12 tháng' }
        ]
      },
      'stt9_h_thng_kiosk_tc_ai_hcm01': {
        name: 'Hệ thống Kiosk TC AI HCM01',
        model: '', brand: 'ISO 9001-2015; 14001-2015; 45001-2018, ISO 27001-2013, Chứng nhận 5S.', origin: '', warranty: '', unit: 'Cái', price: 0,
        specs: [
          { key: 'Màn hình', value: '' },
          { key: 'Kích thước 27” LED backlit; 1920*1080; 16', value: '9; 300cd/m2.' },
          { key: 'Cảm ứng', value: 'Điện dung đa điểm, 10 điểm cùng lúc, loa 2x2w.' },
          { key: 'Kết nối tối thiểu', value: '01x HDMI, 01x VGA, 01x DVI, 01x USB, 01x 12V' },
          { key: 'Chức năng điều khiển', value: '' },
          { key: 'Thông số', value: 'Máy tự động mở khi được cấp điện và tự động tắt vào cuối ngày.' },
          { key: 'Thông số', value: 'Hỗ trợ tùy chọn tính năng nhận diện con người phía trước.' },
          { key: 'Thông số', value: 'Khung sườn' },
          { key: 'Chất liệu', value: 'Khung thép tĩnh điện, chống gỉ, chống ăn mòn tốt, tạo hình và chế tạo bằng công nghệ Laser CNC.' },
          { key: 'Vỏ máy', value: 'Vỏ máy có các kết nối Cổng LAN RJ-45, Cổng USB 2.0; Ngõ luồn dây phía sau.' },
          { key: 'Thông số', value: 'Kiểu dáng sang trọng, bền bỉ.' },
          { key: 'Bộ vi xử lý (CPU)', value: '' },
          { key: 'Thông số', value: 'Intel® Chipset LGA1851, Bộ xử lý Intel® Core™ Ultra 5 235 (24M, upto 5,00 GHz)' },
          { key: 'Bộ nhớ (RAM)', value: '16GB DDR5' },
          { key: 'Ổ cứng chạy hệ điều hành và Lưu trữ dữ liệu', value: 'SSD 512 GB' },
          { key: 'Kết nối trong', value: '01 x HDMI, 01 x DisplayPort, 06 x USB (2.0, 3.0)' },
          { key: 'Kết nối ngoài vỏ máy', value: '01xUSB, 01x RJ45 (LAN), 01 x Power button; 01 x AC220V' },
          { key: 'Máy in nhiệt', value: '' },
          { key: 'Khổ giấy', value: 'Công nghệ in nhiệt trực tiếp, giấy cuộn, khổ giấy 80mm, cắt giấy tự động.' },
          { key: 'Tốc độ in', value: 'Tốc độ in 250mm/s' },
          { key: 'Kết nối', value: 'USB 2.0' },
          { key: 'Thông số', value: 'Cửa nhận giấy từ phía trước' },
          { key: 'Thông số', value: 'Có khóa điều khiển mở thay giấy bằng mô tơ điện tự động, cửa thay giấy từ phía trước dễ dàng thay giấy' },
          { key: 'Đầu đọc Căn cước thẻ chip', value: '' },
          { key: 'Đọc CCCD và giải mã tiếng Việt như', value: 'Hình ảnh, số CCCD, ngày cấp, ngày hết hạn, số CMND, Họ và tên, Ngày tháng năm sinh, Quốc tịch, Giới tính, Dân tộc, Tôn giáo, Tên bố, tên mẹ, tên vợ hoặc chồng, nhận dạng khuôn mặt, quê quán, trường trú ...' },
          { key: 'Kết nối', value: 'USB, Cung cấp SDK cho lập trình. Cung cấp API cho kết nối phần mềm.' },
          { key: 'Kết nối', value: 'USB 2.0' },
          { key: 'Máy Scan A4', value: '' },
          { key: 'Tốc độ quét một mặt A4, 200dpi', value: '40 trang/phút.' },
          { key: 'Tốc độ quét hai mặt A4, 200dpi', value: '80 hình/phút.' },
          { key: 'Cổng kết nối', value: 'USB 2.0' },
          { key: 'Thông số', value: 'Có khả năng scan màu, đen trắng hồ sơ dạng A4, thẻ CCCD, hộ chiếu, thẻ ngân hàng, các loại thẻ cứng khác.' },
          { key: 'Thông số', value: 'Nạp giấy cửa trước; Có cửa nhận giấy dạng khe phía trước như các máy ATM, có khả năng Nhận tài liệu, scan và tự trả lại tài liệu trên cùng khe nhận giấy để thuận tiện việc scan.' },
          { key: 'Nạp giấy phía trên', value: 'Có thể nạp nhiều tài liệu cùng lúc phía trên để scan liên tục nhiều tài liệu và trả tài liệu lại cùng hướng.' },
          { key: 'Thông số', value: 'Có khả năng đọc và mã hóa mã MRZ chuẩn ICAO trên tài liệu.' },
          { key: 'Thông số', value: 'Có khả năng đọc và mã hóa mã vạch 1D (Barecode) và 2D (QRcode)' },
          { key: 'Thông số', value: 'Cảm biến hình ảnh lớn, tốc độ đọc cao, Góc đọc rộng.' },
          { key: 'Camera', value: '' },
          { key: 'Thông số', value: 'Độ phân giải full HD 1920*1080' },
          { key: 'Thông số', value: 'Góc nhìn 65° (tùy chọn 70-90°).' },
          { key: 'Kiểu gắn', value: 'Camera chuyên dụng, kiểu gắn cố định tích hợp' },
          { key: 'Thông số', value: 'Tự động điều chỉnh cân bằng ánh sáng.' },
          { key: 'Micro', value: '' },
          { key: 'Thông số', value: 'Micro thu âm đẳng hướng.' },
          { key: 'Thông số', value: 'Độ nhạy cao, thu âm trong bán kính 2m' },
          { key: 'Chứng nhận của nhà sản xuất Kiosk', value: '' },
          { key: 'Nhà sản xuất được chứng nhận', value: 'ISO 9001-2015; 14001-2015; 45001-2018, ISO 27001-2013, Chứng nhận 5S.' },
          { key: 'Thông số', value: 'Nhà sản xuất có chứng nhận đăng ký thương hiệu Việt Nam.' },
          { key: 'Thông số', value: 'Nhà sản xuất có chứng nhận quyền tác giả thương hiệu Việt.' },
          { key: 'Phần mềm Kiosk dịch vụ công tự động toàn trình', value: '' },
          { key: 'Thông số', value: 'Phần mềm Kiosk Dịch vụ công tự động toàn trình là một giải pháp công nghệ tiên tiến được thiết kế để hoạt động trên Kiosk, nhằm mục đích cung cấp một giải pháp Dịch vụ công tự động toàn trình từ khâu công dân đặt lịch trực tuyến, lấy số thứ tự trực tuyến cho đến khâu cán bộ xử lý và mỗi công dân vào quầy cuối cùng là hiển thị thông tin trên màn hình chung.' },
          { key: 'Bốc số', value: '' },
          { key: 'Thông số', value: 'Tại các điểm giao dịch, công dân có thể tương tác với Kiosk để lấy số thứ tự.' },
          { key: 'Xác thực lịch hẹn', value: 'Công dân đã đặt lịch hẹn trực tuyến có thể nhập mã đặt chỗ hoặc số CCCD, sau đó hệ thống đối soát dữ liệu và in phiếu. Trên phiếu sẽ hiển thị số CCCD của công dân để nhân viên tại quầy dễ dàng đối chiếu với giấy tờ gốc.' },
          { key: 'Lấy số trực tiếp', value: 'Đối với công dân chưa có lịch hẹn, sau khi chọn lĩnh vực dịch vụ, công dân có thể được yêu cầu quét thẻ CCCD gắn chip. Số CCCD sẽ được in trực tiếp lên phiếu cùng với số thứ tự để đảm bảo tính chính xác và duy nhất của lượt giao dịch.' },
          { key: 'Dịch vụ công', value: '' },
          { key: 'Nộp hồ sơ', value: 'Cho phép công dân thực hiện các thao tác liên quan đến việc nộp hồ sơ trực tiếp tại Kiosk.' },
          { key: 'Tra cứu hồ sơ', value: 'Cung cấp chức năng để công dân có thể kiểm tra tình trạng và thông tin về hồ sơ của mình.' },
          { key: 'Tra cứu văn bản', value: 'Cho phép người dùng tìm kiếm và xem các văn bản, quy định liên quan.' },
          { key: 'Đánh giá', value: 'Công dân có thể gửi phản hồi, đánh giá về chất lượng dịch vụ và mức độ hài lòng. Thông tin đánh giá sẽ được lưu trữ kèm theo số định danh cá nhân (CCCD) để phục vụ công tác xác thực và nâng cao chất lượng phục vụ.' },
          { key: 'Chatbox AI', value: 'Hỗ trợ trả lời thủ tục hành chính, tra cứu kết quả hồ sơ bằng ngôn ngữ văn bản/giọng nói đầu vào tự nhiên.' },
          { key: 'Thông số', value: 'Bảo hành 12 tháng' }
        ]
      },
      'stt10_my_tnh_bng_13_inch_ipad_a': {
        name: 'Máy tính bảng 13 inch iPad Air 13-inch Wi-Fi + Cellular 256GB',
        model: '', brand: 'Apple', origin: '', warranty: '', unit: 'Cái', price: 0,
        specs: [
          { key: 'Kích thước màn hình', value: '13 inches' },
          { key: 'Chipset', value: 'Apple M4' },
          { key: 'Dung lượng RAM', value: '8 GB' },
          { key: 'Bộ nhớ trong', value: '256GB' },
          { key: 'Khe sim/eSim', value: 'Có' },
          { key: 'Thông số', value: 'Bảo hành 12 tháng' }
        ]
      },
      'stt11_my_tnh_bng_11_inch_ipad_a': {
        name: 'Máy tính bảng 11 inch iPad Air 11-inch Wi-Fi + Cellular 256GB',
        model: '', brand: 'Apple', origin: '', warranty: '', unit: 'Cái', price: 0,
        specs: [
          { key: 'Kích thước màn hình', value: '13 inches' },
          { key: 'Chipset', value: 'Apple M4' },
          { key: 'Dung lượng RAM', value: '8 GB' },
          { key: 'Bộ nhớ trong', value: '256GB' },
          { key: 'Khe sim/eSim', value: 'Có' },
          { key: 'Thông số', value: 'Bảo hành 12 tháng' }
        ]
      },
      'stt12_my_thu_nhn_vn_tay_bkconte': {
        name: 'Máy thu nhận vân tay BKCONTECH BKCA2020101',
        model: '', brand: 'BKCONTECH', origin: '', warranty: '12 tháng', unit: 'Cái', price: 0,
        specs: [
          { key: 'Kiểu thu nhận', value: 'Lăn, phẳng đơn, 4x4x2 phẳng' },
          { key: 'Độ phân giải', value: '500 dpi' },
          { key: 'Vùng quét (thu nhận) vân tay lăn', value: '' },
          { key: 'Chụm 4 ngón', value: '3,2” x 3,0”;' },
          { key: 'Chụm 2 ngón', value: '3,2” x 3,0”;' },
          { key: 'Vân tay lăn', value: '1,6” x 1,6”' },
          { key: 'Chuẩn giao tiếp', value: 'USB 2.0' },
          { key: 'Các hệ điều hành được hỗ trợ', value: 'Microsoft Windows 10 in 64 bit configuration; Linux Ubuntu' },
          { key: 'Tiêu chuẩn IP', value: 'IP 54' },
          { key: 'Nhiệt độ Vận hành', value: '0°C ÷ 50°C' },
          { key: 'Bảo quản', value: '-20°C ÷ 60°C' },
          { key: 'Độ ẩm', value: '10% ÷ 90% (không ngưng tụ)' },
          { key: 'Màn hình', value: 'Màn thông tin LCD hiển thị 7”' },
          { key: 'Bảo hành', value: '12 tháng' }
        ]
      },
      'stt13_my_thu_nhn_mng_mt_cmitech': {
        name: 'Máy thu nhận mống mắt CMITech BMT-20',
        model: '', brand: 'CMITech', origin: '', warranty: '12 tháng', unit: 'Cái', price: 0,
        specs: [
          { key: 'Thông số', value: 'Kích thước 219 x 161 x 58 mm (8,6 X 6,3 X 2,3 inch);' },
          { key: 'Trọng lượng 680 g (1,5 lbs)- MTF', value: 'Vượt quá 4,0 lp/mm @ > 60% độ tương phản;' },
          { key: 'Độ phân giải pixel', value: '18,4 đến 20 pixel/mm;' },
          { key: 'Độ phân giải pixel hình ảnh Iris', value: '640 X 480 pixel;' },
          { key: 'Đầu ra hình ảnh', value: 'Đạt hoặc vượt ISO 19794-6;' },
          { key: 'Khoảng cách đường quang', value: '350 đến 380 mm;' },
          { key: 'Độ sâu trường', value: '30 mm (1,2 inch);' },
          { key: 'Khoảng cách giữa các đồng tử', value: '40 đến 90mm (1,6 đến 3,5 inch);' },
          { key: 'Thời gian chụp', value: '~ 0,5 giây, tính từ thời điểm đặt đầu đến;' },
          { key: 'Chiếu sáng hồng ngoại để chụp ảnh mống mắt/LED kép', value: 'bước sóng 850 nm (±60%); và 750 nm (±40%);' },
          { key: 'Thông số', value: 'Đèn LED bên trong giúp đồng tử co lại;' },
          { key: 'Thông số', value: 'Đèn LED bên ngoài giúp định vị có sự hỗ trợ của người vận hành;' },
          { key: 'Phạm vi nhiệt độ hoạt động', value: '0 đến 50°C- Độ ẩm: 10 đến 90% RH, không ngưng tụ;' },
          { key: 'Tiêu chuẩn an toàn cho mắt', value: 'IEC 62471, IEC 60825-1; Độ bền: IP64 tiêu chuẩn ngăn chặn xâm nhập;' },
          { key: 'Giao diện', value: 'USB 2.0 USB 2.0 tốc độ cao (500 mA ở 5V);' },
          { key: 'Nguồn điện', value: 'Không cần nguồn điện bổ sung;' },
          { key: 'Khả năng tương thích hệ điều hành', value: 'Windows 7, 8, 8.1 và 10, cả phiên bản 32 và 64 bit Linux Ubuntu 12.04, 14.04 và 16.04 LTS Android 4.0 trở lên;' },
          { key: 'Bảo hành', value: '12 tháng' }
        ]
      },
      'stt14_u_c_th_t_identiv_utrust_4': {
        name: 'Đầu đọc thẻ từ Identiv uTrust 4701 F',
        model: '', brand: 'Identiv', origin: '', warranty: '12 tháng', unit: 'Cái', price: 0,
        specs: [
          { key: 'Thông số', value: 'Giao diện kép đầu đọc thẻ thông minh, tuân thủ theo tiêu chuẩn công nghệ thẻ tiếp xúc ISO / IEC 7816, thẻ không tiếp xúc 13,56 MHz và NFC;' },
          { key: 'Giao diện máy chủ', value: 'USB 2.0 CCIP (USB 1.1/3.0 tương thích);' },
          { key: 'Tốc độ truyền thông', value: '12 Mbps (USB 2.0 tốc độ đầy đủ);' },
          { key: 'Kết nối', value: 'USB 2.0 CCID (USB 1.1/3.0 compliant) 12 Mbps;' },
          { key: 'Tiêu chuẩn', value: 'ISO/ IEC7816, ISO/ IEC14443, ISO/ IEC18092' },
          { key: 'Card Protocol', value: 'T=0, T=1; T=CL;' },
          { key: 'Tốc độ đọc ghi', value: 'Up to 600 kbps, TA1=97;' },
          { key: 'Tốc độ Truyền dữ liệu', value: '106/212/424/848 Kbits/S, tùy thuộc vào thẻ IC;' },
          { key: 'Hệ điều hành', value: 'Window, MacOS, Linux;' },
          { key: 'Nhiệt độ hoạt động', value: '-10° đến 70°C;' },
          { key: 'Độ ẩm hoạt động', value: 'Lên đến 95% RH không ngưng tụ;' },
          { key: 'Kết nối', value: '1.5 m cáp USB với USB Loại A kết nối;' },
          { key: 'Hệ thống Tiêu chuẩn', value: 'ISO/IEC 7816, USB 2.0 Tốc Độ Đầy Đủ, CCID, Microsoft® WHQL;' },
          { key: 'Thời gian bảo hành', value: '12 tháng' }
        ]
      },
      'stt15_thit_b_c_th_nh_aten_uh324': {
        name: 'Thiết bị đọc thẻ nhớ ATEN UH3240',
        model: '', brand: 'ATEN', origin: '', warranty: '12 tháng', unit: 'Cái', price: 0,
        specs: [
          { key: 'Dùng cho', value: 'Máy vi tính hỗ trợ cổng Type C' },
          { key: 'Chức năng', value: 'Xuất hình ảnh Chuyển đổi cổng kết nối USB-C Multiport Dock' },
          { key: 'Đầu ra', value: '' },
          { key: 'Thông số', value: '1 × Gigabit Ethernet' },
          { key: 'Thông số', value: '3 × USB 3.2 Gen 1 Type-A' },
          { key: 'Thông số', value: '1 × SD/SDHC/SDXC, tới 2TB' },
          { key: 'Thông số', value: '1 × microSD/SDHC/SDXC, tới 2TB' },
          { key: 'Thông số', value: '2 × HDMI' },
          { key: 'Thông số', value: '2 Type C' },
          { key: 'Thông số', value: '1 × 3.5mm stereo 4-pole microphone/headphone' },
          { key: 'Thông số', value: '2 Type C' },
          { key: 'Tốc độ truyền dữ liệu', value: 'USB 3.2 Gen 1, 5Gbps' },
          { key: 'Độ phân giải tối đa', value: 'Single lên 8K; Dual HDMI 4K' },
          { key: 'Jack kết nối', value: 'Type-C' },
          { key: 'Thời gian bảo hành', value: '12 tháng' }
        ]
      },
      'stt16_my_c_th_nh_aten_uh3240': {
        name: 'Máy đọc thẻ nhớ ATEN UH3240',
        model: '', brand: 'ATEN', origin: '', warranty: '12 tháng', unit: 'Cái', price: 0,
        specs: [
          { key: 'Dùng cho', value: 'Máy vi tính hỗ trợ cổng Type C' },
          { key: 'Chức năng', value: 'Xuất hình ảnh Chuyển đổi cổng kết nối USB-C Multiport Dock' },
          { key: 'Đầu ra', value: '' },
          { key: 'Thông số', value: '1 × Gigabit Ethernet' },
          { key: 'Thông số', value: '3 × USB 3.2 Gen 1 Type-A' },
          { key: 'Thông số', value: '1 × SD/SDHC/SDXC, tới 2TB' },
          { key: 'Thông số', value: '1 × microSD/SDHC/SDXC, tới 2TB' },
          { key: 'Thông số', value: '2 × HDMI' },
          { key: 'Thông số', value: '2 Type C' },
          { key: 'Thông số', value: '1 × 3.5mm stereo 4-pole microphone/headphone' },
          { key: '2 cổng USB-C Female trên dock', value: '1 × USB-C 3.2 Gen 1: truyền dữ liệu 5 Gbps.\n1 × USB-C PD: cấp nguồn/sạc, hỗ trợ PD 3.0 tới 100 W.' },
          { key: 'Tốc độ truyền dữ liệu', value: 'USB 3.2 Gen 1, 5Gbps' },
          { key: 'Độ phân giải tối đa', value: 'Single lên 8K; Dual HDMI 4K' },
          { key: 'Jack kết nối', value: 'Type-C' },
          { key: 'Thời gian bảo hành', value: '12 tháng' }
        ]
      },
